### ISSUE TITLE
画网格的地方是否可以优化一下呢，改成提前绘制为picture，然后在ondraw 只绘制picture

### ISSUE THREAD

**Issue by tianshaokai** [zincPower/UI2018#1]
1.如题
2.按照此方法修改是否会减少canvas 的绘制
只是想和作者讨论一下，学习安卓

**Comment by zincPower** [comment]
您好，使用双缓冲确实可以让GPU先进行处理，是一个不错的优化方向。

但至于第二点，说减少 canvas 的绘制，我不太懂您具体想表达的意思。双缓冲只是提前了绘制，让GPU先处理，等到真正需要使用的时候，直接将缓冲区的 Bitmap 展示。按这种说法，应该说是多了一次绘制。

**Comment by tianshaokai** [comment]
@zincPower  这样是不是不用每次在onDraw 都去绘制了一次网格呢？？

**Comment by tianshaokai** [comment]
@zincPower  绘制缓冲区的bitmap, 比 在onDraw 里 直接绘制 网格，哪个比较节省gpu 呢

**Comment by zincPower** [comment]
画网格的地方确实可以单独抽取出来绘制成Bitmap，避免动画过程中重复的绘制，可以减轻GPU的消耗。

但这里考虑到两点所以暂时不进行该方向的代码优化：
1、这个 Demo 主要是讲述属性动画，所以尽可能的避免一些干扰因素。
2、个人觉得不需要过早优化，因为没到达性能优化点，所以暂时不考虑。

其实这个Demo之前在悦跑圈的时候已经是有在线上的项目“悦跑团”中使用，这次进行了一些重构，核心的部分没有改动。

**Comment by tianshaokai** [comment]
ok 谢谢
