### ISSUE TITLE
作者看看这是不是初始化了两个实例，按理说不应该啊？

### ISSUE THREAD

**Issue by tianshaokai** [zincPower/UI2018#2]
![image](https://user-images.githubusercontent.com/6706496/55315013-f34cb500-549d-11e9-992e-3ae59be7021d.png)
![image](https://user-images.githubusercontent.com/6706496/55315169-5a6a6980-549e-11e9-9bfd-5e556653fe15.png)

**Comment by zincPower** [comment]
您好，感谢您仔细的查看并分析我的代码。😄

我想确定您在拍内存快照时，是不是没有先点击旁边的 “小垃圾桶”的图标进行强制执行GC回收？

因为我自己在操作时，如果没有点击“小垃圾桶”的话，确实实例是大于1个的，因为这个时候jvm的内存是充足的，GC还未进行回收。所以需要点击 “小垃圾桶”，强制执行 GC 进行内存回收，回收后的实例数量为1，是正常的情况。

不知道这是否是您需要的答案？等待您的答复。

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/55794707-7acaa180-5af8-11e9-95ab-f2e228b9fd97.png)

**Comment by tianshaokai** [comment]
我就是连续进入了好多次这个activity，然后最后一次打开了profile, 并且点击了gc 按钮

**Comment by tianshaokai** [comment]
好，谢谢，我有时间再看看啊

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/55845968-907eac00-5b76-11e9-83ab-85ffdb56b153.png)

我多次进入后，先点击gc按钮，点击了好几次，圈起来的这段时间是点击gc，然后查看内存快照，我的手机是红米 内存小

**Comment by tianshaokai** [comment]
作者可否加我qq交流一下 1575640686，或者我加你也可以，学习一下安卓

**Comment by zincPower** [comment]
你最后一张图的内存不是已经正常了么？现在的手机内存至少也有2G，给app分配的有64M、128M甚至更多，所以内存小和这个场景不相关。

嗯嗯。我加你QQ，我们共同探讨，一起学习，一起进步。
